version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: npm run start-docker
    volumes:
      - ./uploads:/src/app/uploads
      - ./log:/src/app/log
      - ./src:/src/app/src
    links:
      - redis
      - mongodb
    depends_on:
      - redis
      - mongodb
    environment: 
      - MONGODB_URL=mongodb://mongodb:27017/test
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    env_file:
      - .env
  redis:
    image: redis:4-alpine
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./datadb:/data/db